In [1]:
import tensorflow as tf

For neutral network in tensorflow, we use:
- Tensor to represent data
- Computation graphs to build neutral network
- Session to execute computation graphs

# Tensor: Basic unit of data
- Scalars (0D tensors)
- Vector (1D tensors)
- Matrix (2D tensors)

## Scalars (0D tensors)

In [2]:
random_float = tf.random.uniform(shape = ())             # Declare a random float (scalar).
print(random_float)

tf.Tensor(0.50159764, shape=(), dtype=float32)


In [3]:
a = tf.constant(5.0)                                     # Declare a float (scalar).
print(a)

tf.Tensor(5.0, shape=(), dtype=float32)


## Vector (1D tensors)

In [4]:
zero_vector = tf.zeros(shape = (2))                      # Declare a zero vector with two elements, default type: float.
print(zero_vector)
zero_vector1 = tf.zeros(shape = (2), dtype = tf.int32)   # Declare two 2*2 constant matrices A and B, change float to int
print(zero_vector1)

tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int32)


## Matrix (2D tensors)

In [5]:
A = tf.constant([[1., 2.], [3., 4.]])                    # Declare a 2×2 constant matrix
print(A)
B = tf.constant([[5., 6.], [7., 8.]])
print(B)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


## Attributes of tensor

A tensor have 3 important attributes: shape, data type and value. 

You can use the shape, data type attribute and the numpy() method to fetch them. For example:

In [6]:
print(A.shape)      
print(A.dtype)      
print(A.numpy())     #  numpy() method of a tensor is to return a NumPy array whose value equals the value of the tensor.
print(A.ndim)

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]
2


In [7]:
import keras
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [8]:
print(train_images.ndim)

3


In [9]:
print(train_images.shape)

(60000, 28, 28)


In [10]:
print(train_images.dtype)

uint8


What we have here is a 3D tensor of 8-bit integers. More precisely, it is an array of 60,000 matrices of 28x28 integers. 

Each such matrix is a grayscale image, with coefficients between 0 and 255.

Let’s display the 4th digit in this 3D tensor, using the library Matplotlib.

In [11]:
digit = train_images[4]
import matplotlib.pyplot as plt
plt.imshow(digit, cmap = plt.cm.binary)        # cmap: color map, e.g.: cmap = plt.cm.RdGy
plt.show()

<Figure size 640x480 with 1 Axes>

In [12]:
my_slice = train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [13]:
my_slice = train_images[10:100, :, :]
print(my_slice.shape)

(90, 28, 28)


In [14]:
my_slice = train_images[10:100, 0:28, 0:28]
print(my_slice.shape)

(90, 28, 28)


# Computation Graphs
Build the process of computation and input it inot y node, but without results.

<img src = "./img/1_computation_graph.png" width= 600>

In [15]:
A = tf.constant([[1., 2.], [3., 4.]])                   # Declare a 2×2 constant matrix
B = tf.constant([[5., 6.], [7., 8.]])

C = tf.add(A, B)                                        # Compute the elementwise sum of A and B.
print(C)

D = tf.matmul(A, B)                                     # Compute the multiplication of A and B.
print(D)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [16]:
x = tf.constant([[1.0, 2.0]])                           # Build a graph.
w = tf.constant([[3.0], [4.0]])
y = tf.matmul(x, w)
print(y)

tf.Tensor([[11.]], shape=(1, 1), dtype=float32)


# Session
Execute the operation of the node in computation graphs (y node).

<img src = "./img/2_session.png" width= 600>

In [17]:
with tf.compat.v1.Session() as sess:  #
    x = tf.constant([[1.0, 2.0]])
    w = tf.constant([[3.0], [4.0]])
    y = tf.matmul(x, w)
    print(sess.run(y))

[[11.]]


# Real-world examples of data tensors

- Vector data: 2D tensors of shape (samples, features).
- Timeseries data or sequence data: 3D tensors of shape (samples, timesteps, features).
- Images: 4D tensors of shape (samples, width, height, channels) or (samples, channels, width, height).
- Video: 5D tensors of shape (samples, frames, width, height, channels) or (samples, frames, channels, width, height).

## Vector data

A batch of data will be encoded as a 2D tensor (i.e. an array of vectors),
where the first axis is the <font color=red>**"samples axis"**</font> and the second axis is the <font color=red>**"features axis"**</font>.

**For example,** an actuarial dataset of people, where we consider for each person their age, zipcode, and income. Each person can be characterized as a vector of 3 values, and thus an entire dataset of 100,000 people can be stored in a 2D tensor of shape (100000, 3).

## Timeseries data or sequence data

Each sample can be encoded as a sequence of vectors (a 2D tensor), and thus a batch of data will be encoded as a 3D tensor.

**The time axis will always be the second axis (axis of index 1), by convention.** Let’s have a look at a few examples:

A dataset of stock prices. Every minute, we store the current price of the stock, the
highest price in the past minute and the lowest price in the past minute. Thus every
minute is encoded as a 3D vector, an entire day of trading is encoded as a 2D tensor of
shape (390, 3) (there are 390 minutes in a trading day), and 250 days worth of data can
be stored in a 3D tensor of shape (250, 390, 3). Here, each sample would be one day
worth of data.

<img src = "./img/3_series.png" width = 500>

## Image data

A batch of 128 grayscale images of size 256x256 could thus be stored in a tensor of shape 
(128, 256, 256, 1), and a batch of 128 color images could be stored in a tensor of shape (128, 256, 256, 3).

<img src = "./img/4_image.png" width = 350>

- Google, places the color depth axis at the end, as we just saw: (samples, width, height, **color_depth**).

- Theano places the color depth axis right after the batch axis: (samples, **color_depth**, width, height).

## Video data

Video data needs 5D tensors. A video can be understood as a sequence of frames, each frame being a color image.
Since each frame can be stored in a 3D tensor (width, height, color_depth), then a sequence of frames can be 
stored in 4D tensor (frames, width, height, color_depth), and thus a batch of different videos can be stored 
in a 5D tensor of shape (samples, frames, width, height, color_depth).

For instance, a 60-second, 256x144 YouTube video clip sampled at 4 frames per second would have 240 frames. 
A batch of 4 such video clips would be stored in a tensor of shape (4, 240, 256, 144, 3).